#!/usr/bin/env sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

# Lint all selected files
echo "$FILES" | xargs ./node_modules/.bin/biome check --no-errors-on-unmatched

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
